-- MySQL Script generated by MySQL Workbench
-- Sat Sep 26 11:14:19 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema comp9321_ass2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `comp9321_ass2` ;

-- -----------------------------------------------------
-- Schema comp9321_ass2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `comp9321_ass2` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `comp9321_ass2` ;

-- -----------------------------------------------------
-- Table `comp9321_ass2`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comp9321_ass2`.`user` ;

CREATE TABLE IF NOT EXISTS `comp9321_ass2`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `email` VARCHAR(145) NULL,
  `birthyear` INT NULL,
  `address` VARCHAR(245) NULL,
  `creditcard` VARCHAR(45) NULL,
  `ban` TINYINT(1) NULL,
  `verified` TINYINT(1) NULL,
  `uuid` VARCHAR(45) NULL,
  `salt` VARCHAR(200) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comp9321_ass2`.`item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comp9321_ass2`.`item` ;

CREATE TABLE IF NOT EXISTS `comp9321_ass2`.`item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `authors` VARCHAR(250) NULL,
  `type` VARCHAR(45) NULL,
  `publication_date` DATE NULL,
  `venue` VARCHAR(45) NULL,
  `price` DOUBLE NULL,
  `paused` TINYINT(1) NULL,
  `ban` TINYINT(1) NULL,
  `quantity` INT NULL,
  `imageURL` VARCHAR(200) NULL,
  `seller_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Item_user_idx` (`seller_id` ASC),
  CONSTRAINT `fk_Item_user`
    FOREIGN KEY (`seller_id`)
    REFERENCES `comp9321_ass2`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comp9321_ass2`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comp9321_ass2`.`order` ;

CREATE TABLE IF NOT EXISTS `comp9321_ass2`.`order` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `created` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_has_OrderItem_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_OrderItem_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `comp9321_ass2`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comp9321_ass2`.`orderItem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comp9321_ass2`.`orderItem` ;

CREATE TABLE IF NOT EXISTS `comp9321_ass2`.`orderItem` (
  `id` INT NOT NULL,
  `count` INT NULL,
  `item_id` INT NOT NULL,
  `order_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_OrderItem_Item1_idx` (`item_id` ASC),
  INDEX `fk_OrderItem_Order1_idx` (`order_id` ASC),
  CONSTRAINT `fk_OrderItem_Item1`
    FOREIGN KEY (`item_id`)
    REFERENCES `comp9321_ass2`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrderItem_Order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `comp9321_ass2`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comp9321_ass2`.`cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comp9321_ass2`.`cart` ;

CREATE TABLE IF NOT EXISTS `comp9321_ass2`.`cart` (
  `user_id` INT NOT NULL,
  `item_id` INT NOT NULL,
  `count` INT NULL,
  `added` DATETIME NULL,
  `removed` DATETIME NULL,
  INDEX `fk_Cart_user1_idx` (`user_id` ASC),
  INDEX `fk_cart_item1_idx` (`item_id` ASC),
  PRIMARY KEY (`item_id`, `user_id`),
  CONSTRAINT `fk_Cart_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `comp9321_ass2`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_item1`
    FOREIGN KEY (`item_id`)
    REFERENCES `comp9321_ass2`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comp9321_ass2`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comp9321_ass2`.`admin` ;

CREATE TABLE IF NOT EXISTS `comp9321_ass2`.`admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
